/* ===================================================================
   Script: 生成所有 Industry Skills + Brand Skills
   运行: node scripts/generate-skills.js
   =================================================================== */

const fs = require('fs');
const path = require('path');

const BASE = path.join(__dirname, '..', 'src', 'skills');

/* ═══════════════════════════════════════════════════════════════════
   Industries (22)
   ═══════════════════════════════════════════════════════════════════ */
const industries = [
  { id:'fashion',en:'Fashion',zh:'服装',icon:'Shirt',cat:'official',
    kw:['clothing','apparel','dress','shirt','jacket','coat','pants','jeans','sweater','hoodie','suit','fashion','wear','outfit','春夏','秋冬'],
    visual:'Clean studio lighting, natural poses on models, fabric texture close-ups, lifestyle styling. E-commerce standard: white/neutral backgrounds for main images, lifestyle shots for detail pages.',
    zhVisual:'干净影棚光，模特自然姿态，面料质感特写，生活方式穿搭。电商标准：白底主图+场景详情页。',
    sp:['Latest design','Fabric quality','Comfort','Fit','Versatile styling','Seasonal collection','Limited edition'],
    zhSP:['当季新款','面料质感','舒适度','版型合身','百搭','季节新款','限量款'],
    term:['Slim fit','Oversized','Cotton','Linen','Silk','Wool','Knit','Denim','Casual','Business'],
    zhTerm:['修身','宽松','棉','亚麻','真丝','羊毛','针织','牛仔','休闲','商务'],
    comp:['Zara','H&M','UNIQLO','COS','Massimo Dutti'],
    platforms:['taobao','amazon','shopee','shein','douyin','tiktok','shopify'],
    tips:'Fashion products typically need 6-8 lifestyle images + 3-5 flat lays + detail close-ups. Vertical video (9:16) for Douyin/TikTok, square (1:1) for marketplaces.',
    zhTips:'服装建议6-8张场景图+3-5张平铺图+细节特写。抖音竖屏9:16，电商平台方形1:1。'},
  { id:'shoes',en:'Shoes',zh:'鞋靴',icon:'Shoe',cat:'official',
    kw:['shoes','sneakers','boots','heels','sandals','slippers','loafers','鞋','运动鞋','靴子','高跟鞋','凉鞋','拖鞋'],
    visual:'360-degree product views, sole texture close-up, insole detail, lifestyle on-feet shots. Clean reflections for leather, matte for canvas/suede.',
    zhVisual:'360度产品展示，鞋底纹理特写，鞋垫细节，上脚场景图。皮革需高光反射，帆布/麂皮需哑光处理。',
    sp:['Comfortable sole','Breathable material','Anti-slip','Lightweight','Premium leather','Handcrafted','Orthopedic support'],
    zhSP:['舒适鞋底','透气材质','防滑耐磨','轻盈','头层牛皮','手工制作','足弓支撑'],
    term:['Running','Casual','Formal','Athletic','Canvas','Leather','Suede','Mesh','Waterproof','Slip-on'],
    zhTerm:['跑步','休闲','正装','运动','帆布','皮革','麂皮','网面','防水','一脚蹬'],
    comp:['Nike','Adidas','Clarks','Cole Haan','ECCO'],
    platforms:['taobao','amazon','shopee','temu','tiktok'],
    tips:'Shoes: show top, side, sole, heel, and detail views. Include size chart for marketplaces.',
    zhTips:'鞋类：展示顶面、侧面、鞋底、后跟、细节。电商平台需附尺码表。'},
  { id:'bags',en:'Bags',zh:'箱包',icon:'Briefcase',cat:'official',
    kw:['bag','handbag','backpack','wallet','purse','luggage','suitcase','tote','包','手袋','背包','钱包','行李箱'],
    visual:'Interior shots showing compartments, strap details, material texture. Lifestyle: urban commuting, travel, business settings.',
    zhVisual:'内部结构展示（隔层/口袋），肩带细节，皮质纹理。场景：都市通勤、旅行、商务。',
    sp:['Premium leather','Large capacity','Water-resistant','Lightweight','Multi-compartment','Anti-theft','USB charging port'],
    zhSP:['头层牛皮','大容量','防水','轻便','多隔层','防盗','USB充电'],
    term:['Backpack','Tote','Crossbody','Clutch','Duffel','Carry-on','Expandable','RFID protected'],
    zhTerm:['双肩包','托特包','斜挎包','手拿包','旅行袋','登机箱','可扩展','RFID防盗'],
    comp:['Tumi','Samsonite','Longchamp','Coach','Herschel'],
    platforms:['taobao','amazon','shopee','lazada','shopify'],
    tips:'Bags: show empty interior, loaded interior, worn on model, and close-up of zippers/stitching.',
    zhTips:'箱包：展示空包内部、装满效果、模特上身、拉链走线特写。'},
  { id:'beauty',en:'Beauty',zh:'美妆',icon:'Sparkles',cat:'official',
    kw:['makeup','cosmetics','lipstick','foundation','eyeshadow','mascara','blush','口红','粉底','眼影','睫毛膏','腮红','化妆'],
    visual:'Soft diffused lighting, swatch close-ups on skin, before/after comparisons. Clean minimal background with soft shadows.',
    zhVisual:'柔光散射光，皮肤试色特写，前后对比。干净简约背景配柔和阴影。',
    sp:['Long-lasting','Waterproof','Natural ingredients','Cruelty-free','Vegan','Full coverage','Lightweight formula'],
    zhSP:['持久不脱妆','防水','天然成分','零残忍','纯素','高遮瑕','轻薄配方'],
    term:['Matte','Glossy','Dewy','Transfer-proof','Buildable','Sheer','Pigmented','K-Beauty','Clean Beauty'],
    zhTerm:['哑光','光泽','水光','不转移','可叠加','清透','高显色','韩妆','纯净美妆'],
    comp:['MAC','Fenty Beauty','Estée Lauder','L\'Oréal','Innisfree'],
    platforms:['taobao','douyin','tiktok','xiaohongshu','amazon'],
    tips:'Beauty: swatch photos (3-5 colors), before/after, ingredient highlight, and tutorial-style videos.',
    zhTips:'美妆：试色图3-5色，前后对比，成分展示，教程风格视频。'},
  { id:'skincare',en:'Skincare',zh:'护肤',icon:'Droplets',cat:'official',
    kw:['skincare','moisturizer','serum','sunscreen','toner','cleanser','cream','精华','面霜','防晒','爽肤水','洁面','护肤'],
    visual:'Dropper/squeeze tube product shots, texture on hand, ingredient close-ups. Clean, clinical-luxury aesthetic.',
    zhVisual:'滴管按压产品图，手上质地展示，成分特写。干净临床+奢华感。',
    sp:['Hyaluronic acid','Vitamin C','Retinol','Niacinamide','Dermatologist tested','Oil-free','Hypoallergenic'],
    zhSP:['玻尿酸','维生素C','视黄醇','烟酰胺','皮肤科测试','无油','低敏'],
    term:['Serum','Essence','Ampoule','Exfoliant','Toner','Peptide','Ceramide','Barrier repair'],
    zhTerm:['精华液','精华水','安瓶','去角质','爽肤水','胜肽','神经酰胺','屏障修护'],
    comp:['SK-II','La Mer','Estée Lauder','CeraVe','The Ordinary'],
    platforms:['taobao','douyin','xiaohongshu','amazon','shopee'],
    tips:'Skincare: texture shots, ingredient breakdowns, before/after (4-8 weeks), and educational content.',
    zhTips:'护肤：质地展示，成分解析，4-8周前后对比，教育内容。'},
  { id:'jewelry',en:'Jewelry',zh:'珠宝',icon:'Gem',cat:'official',
    kw:['jewelry','necklace','ring','bracelet','earrings','pendant','diamond','gold','silver','项链','戒指','手链','耳环','钻石','金','银'],
    visual:'Macro close-ups on reflective surfaces, 360° rotating view, model wearing shots. Dark velvet backgrounds for luxury feel.',
    zhVisual:'微距反光面特写，360度旋转，模特佩戴。深色丝绒背景营造奢华感。',
    sp:['18K Gold','925 Sterling Silver','Natural gemstone','Handcrafted','Certified diamond','Hypoallergenic','Lifetime warranty'],
    zhSP:['18K金','925纯银','天然宝石','手工制作','认证钻石','防过敏','终身保修'],
    term:['Solitaire','Halo','Pave','Carat','Clarity','Plating','Engraved','Custom'],
    zhTerm:['单钻','围镶','密镶','克拉','净度','电镀','刻字','定制'],
    comp:['Tiffany','Cartier','Pandora','Swarovski','周大福'],
    platforms:['taobao','etsy','amazon','shopify','shopee'],
    tips:'Jewelry: use macro lens effect, show on different skin tones, include size reference (coin/credit card).',
    zhTips:'珠宝：微距效果，不同肤色佩戴展示，尺寸参照物（硬币/卡片）。'},
  { id:'watch',en:'Watch',zh:'手表',icon:'Clock',cat:'official',
    kw:['watch','timepiece','chronograph','smartwatch','mechanical','quartz','手表','腕表','计时','智能手表','机械','石英'],
    visual:'Detailed dial close-ups, leather strap texture, metal bracelet sheen, wrist-worn lifestyle. Classic luxury watch aesthetic.',
    zhVisual:'表盘特写，皮带纹理，金属表带光泽，手腕佩戴场景。经典奢华腕表美学。',
    sp:['Swiss movement','Sapphire crystal','Water resistant','Stainless steel','Genuine leather strap','Chronograph','Limited edition'],
    zhSP:['瑞士机芯','蓝宝石镜面','防水','不锈钢','真皮表带','计时功能','限量版'],
    term:['Automatic','Quartz','Diver','Dress','Chronograph','Tourbillon','Skeleton'],
    zhTerm:['自动机械','石英','潜水表','正装表','计时码表','陀飞轮','镂空'],
    comp:['Rolex','Omega','Casio','Daniel Wellington','Seiko'],
    platforms:['amazon','taobao','ebay','shopify','shopee'],
    tips:'Watch: show crown detail, case back, clasp mechanism, and a lume shot (glow in dark).',
    zhTips:'手表：表冠细节，底盖，表扣，夜光效果。'},
  { id:'electronics',en:'Electronics',zh:'3C数码',icon:'Cpu',cat:'official',
    kw:['phone','laptop','headphone','earbuds','tablet','speaker','charger','cable','camera','手机','电脑','耳机','平板','音箱','充电器','相机'],
    visual:'Clean white/grey backgrounds, angled product shots showing ports and features, lifestyle: desk setup, commuting, gym.',
    zhVisual:'白色/灰色背景，斜角度展示接口和功能。场景：桌面办公、通勤、健身。',
    sp:['Latest chip','Long battery life','Hi-Fi audio','4K display','Fast charging','5G','AI-powered'],
    zhSP:['最新芯片','超长续航','高保真音质','4K显示','快充','5G','AI智能'],
    term:['ANC','Wireless','USB-C','Bluetooth','OLED','HDR','IP rating','Watt','Hz'],
    zhTerm:['主动降噪','无线','USB-C','蓝牙','OLED','HDR','防水等级','瓦','赫兹'],
    comp:['Apple','Samsung','Sony','Bose','Xiaomi'],
    platforms:['amazon','taobao','jd','shopee','temu'],
    tips:'Electronics: show all ports, include comparison chart, highlight key specs with icons.',
    zhTips:'3C：展示所有接口，附参数对照表，图标化关键规格。'},
  { id:'furniture',en:'Furniture',zh:'家具',icon:'Sofa',cat:'official',
    kw:['sofa','table','chair','bed','desk','shelf','cabinet','wardrobe','沙发','桌子','椅子','床','书桌','书架','柜子','衣柜'],
    visual:'Room setting contextual shots, dimension-overlay photos, material close-up (wood grain, fabric weave). Warm natural lighting.',
    zhVisual:'房间场景图，尺寸标注图，材质特写（木纹、织物）。温暖自然光。',
    sp:['Solid wood','Ergonomic design','Easy assembly','Sturdy frame','Eco-friendly','Modular','Storage'],zhSP:['实木','人体工学','易安装','坚固框架','环保','模块化','储物功能'],
    term:['Hardwood','Veneer','Upholstered','Modular','Foldable','Wall-mounted','Reclining'],
    zhTerm:['硬木','贴皮','软包','模块化','可折叠','壁挂','可躺'],
    comp:['IKEA','MUJI','West Elm','Crate & Barrel','Wayfair'],
    platforms:['amazon','taobao','shopify','wayfair'],
    tips:'Furniture: show dimensions clearly, include room visualization, show assembly process.',
    zhTips:'家具：清晰标注尺寸，房间效果图，安装过程。'},
  { id:'home-decor',en:'Home Decor',zh:'家居装饰',icon:'Lamp',cat:'official',
    kw:['lamp','candle','rug','curtain','cushion','vase','frame','mirror','carpet','灯','蜡烛','毯子','窗帘','靠垫','花瓶','画框','镜子','地毯'],
    visual:'Styled vignettes, flat-lay styling, before/after room transformation. Warm, inviting lighting with lifestyle context.',
    zhVisual:'风格化静物，平铺造型，前后改造对比。温暖灯光+生活场景。',
    sp:['Handmade','Unique design','Premium material','Gift-ready','Eco-friendly','Artisan crafted','Limited edition'],
    zhSP:['手工制作','独特设计','优质材质','送礼佳品','环保','匠人制作','限量'],
    term:['Bohemian','Minimalist','Vintage','Contemporary','Rustic','Scandinavian','Boho'],
    zhTerm:['波西米亚','极简','复古','当代','田园','北欧风','波西风'],
    comp:['Zara Home','H&M Home','MUJI','Anthropologie','West Elm'],
    platforms:['etsy','amazon','taobao','shopify','pinterest'],
    tips:'Home Decor: styled room shots, flat-lay compositions, close-up texture plays well.',
    zhTips:'家居装饰：场景搭配图，平铺摆拍，材质质感特写。'},
  { id:'kitchen',en:'Kitchen',zh:'厨房用品',icon:'ChefHat',cat:'official',
    kw:['pot','pan','knife','blender','coffee maker','mug','plate','bowl','cookware','锅','刀','搅拌机','咖啡机','杯子','盘子','碗','厨具'],
    visual:'Food preparation context, steam/action shots, organized kitchen counter. Clean bright lighting, overhead and 45° angles.',
    zhVisual:'烹饪场景，蒸汽动态，整洁台面。明亮灯光，俯拍和45度角。',
    sp:['Non-stick','Stainless steel','Dishwasher safe','Heat resistant','Ergonomic handle','Stackable','Multi-purpose'],
    zhSP:['不粘','不锈钢','洗碗机安全','耐高温','人体工学手柄','可叠放','多功能'],
    term:['Cast iron','Non-stick','Double-walled','Silicone','Bamboo','Ceramic','Tempered glass'],
    zhTerm:['铸铁','不粘','双层','硅胶','竹制','陶瓷','钢化玻璃'],
    comp:['KitchenAid','Le Creuset','OXO','Joseph Joseph','Zwilling'],
    platforms:['amazon','taobao','shopee','temu'],
    tips:'Kitchen: action shots (cooking/pouring), clean product on white, size comparison.',
    zhTips:'厨房用品：动作场景（烹饪/倾倒），白底产品图，尺寸对比。'},
  { id:'pet',en:'Pet',zh:'宠物用品',icon:'PawPrint',cat:'official',
    kw:['dog','cat','pet bed','leash','collar','bowl','toy','cage','aquarium','狗','猫','窝','牵引绳','项圈','碗','玩具','笼子','鱼缸'],
    visual:'Happy pets using the product, outdoor/ indoor natural settings, close-ups of pet interaction. Warm, joyful aesthetic.',
    zhVisual:'开心宠物使用产品，室内外自然场景，宠物互动特写。温暖欢乐风格。',
    sp:['Safe material','Chew-resistant','Easy clean','Vet recommended','Comfortable','Non-toxic','Adjustable'],
    zhSP:['安全材质','耐咬','易清洁','兽医推荐','舒适','无毒','可调节'],
    term:['Orthopedic','Cooling','Reflective','Waterproof','Organic','Grain-free','Harness'],
    zhTerm:['矫形','降温','反光','防水','有机','无谷','胸背带'],
    comp:['Chewy','Petco','Purina','Royal Canin','KONG'],
    platforms:['amazon','taobao','shopee','temu','shopify'],
    tips:'Pet: show product on real pets, include size guide per breed, show play and rest use cases.',
    zhTips:'宠物：真实宠物使用，按品种尺寸指南，玩耍和休息场景。'},
  { id:'food',en:'Food',zh:'食品',icon:'Utensils',cat:'official',
    kw:['food','snack','tea','coffee','chocolate','cookie','noodle','rice','candy','snack','食品','零食','茶','咖啡','巧克力','饼干','面','米','糖果'],
    visual:'Appetizing food photography with steam/warmth, ingredient showcase, serving suggestions. Warm color tones, natural window light.',
    zhVisual:'诱人美食摄影（蒸汽/温热感），食材展示，食用建议。暖色调，自然窗光。',
    sp:['Organic','Non-GMO','No additives','Farm fresh','Artisanal','Traditional recipe','Rich flavor'],
    zhSP:['有机','非转基因','无添加','农场直供','手工制作','传统配方','浓郁口感'],
    term:['Plant-based','Gluten-free','Keto','Vegan','Probiotic','Cold brew','Single origin'],
    zhTerm:['植物基','无麸质','生酮','纯素','益生菌','冷萃','单一产地'],
    comp:['Starbucks','Nestlé','Oatly','三只松鼠','良品铺子'],
    platforms:['amazon','taobao','shopee','douyin','tiktok'],
    tips:'Food: hero shot (prepared), package shot, ingredient lay-down, nutrition facts chart.',
    zhTips:'食品：成品大图，包装图，食材平铺，营养成分表。'},
  { id:'drinks',en:'Drinks',zh:'饮品',icon:'Wine',cat:'official',
    kw:['drink','wine','beer','juice','soda','water','whiskey','champagne','tea drink','饮品','酒','啤酒','果汁','汽水','水','威士忌','香槟','茶饮'],
    visual:'Pour shots with dynamic splashes, condensation/sweat drops on bottles, ice cube detail. Refreshing cool aesthetic.',
    zhVisual:'倾倒动态水花，瓶身冷凝水滴，冰块细节。清爽冰感美学。',
    sp:['Naturally brewed','Cold-pressed','Zero sugar','Premium ingredients','Small batch','Award-winning','Refreshing taste'],
    zhSP:['天然酿造','冷压','零糖','优质原料','小批量','获奖','清爽口感'],
    term:['Craft','Cold brew','Sparkling','Infused','Barrel-aged','Single malt','Estate'],
    zhTerm:['精酿','冷萃','气泡','浸泡','桶陈','单一麦芽','庄园'],
    comp:['Coca-Cola','Starbucks','Nespresso','农夫山泉','三顿半'],
    platforms:['taobao','douyin','tiktok','amazon','shopee'],
    tips:'Drinks: cold product with condensation, pour shot, lifestyle drinking scene, ingredient highlight.',
    zhTips:'饮品：冰镇冷凝效果，倾倒动态，饮用场景，原料展示。'},
  { id:'sports',en:'Sports',zh:'运动',icon:'Dumbbell',cat:'official',
    kw:['fitness','yoga','gym','running','cycling','swim','hiking','健身','瑜伽','跑步','骑行','游泳','登山','运动'],
    visual:'Action shots in use, sweat and dynamic movement, gym/outdoor context. Energetic with motion blur, bold lighting.',
    zhVisual:'使用中动态拍摄，汗水动感，健身/户外场景。动感模糊，强烈光线。',
    sp:['High performance','Breathable','Quick-dry','Compression','Lightweight','Durable','Anti-odor'],
    zhSP:['高性能','透气','速干','压缩','轻量','耐用','防臭'],
    term:['Moisture-wicking','Compression','HIIT','Cross-training','Recovery','Flexibility','Shock absorption'],
    zhTerm:['吸湿排汗','压缩','高强度间歇','交叉训练','恢复','柔韧','减震'],
    comp:['Nike','Adidas','Lululemon','Under Armour','迪卡侬'],
    platforms:['amazon','taobao','shopee','tiktok','douyin'],
    tips:'Sports: action shots, fabric tech close-ups, size+fit guide, sport-specific use case.',
    zhTips:'运动：动态抓拍，面料科技特写，尺码指南，专项运动场景。'},
  { id:'outdoor',en:'Outdoor',zh:'户外',icon:'Trees',cat:'official',
    kw:['camping','tent','sleeping bag','lantern','backpack','hiking','fishing','knife','帐篷','睡袋','营地灯','登山','钓鱼','刀具','户外'],
    visual:'Real wilderness setting, golden hour lighting, gear in use on location. Adventurous, rugged yet premium aesthetic.',
    zhVisual:'真实野外场景，黄金时刻光线，恶劣环境中装备展示。冒险感+高级质感。',
    sp:['Waterproof','Windproof','Ultralight','All-season','Compact','Ripstop','Survival ready'],
    zhSP:['防水','防风','超轻','四季','便携','防撕裂','生存级别'],
    term:['4-season','Trekking pole','Base layer','BUG net','Bivy','Tarp','Bear canister'],
    zhTerm:['四季','登山杖','打底层','防虫网','露营袋','天幕','防熊罐'],
    comp:['The North Face','Patagonia','Arc\'teryx','Columbia','Black Diamond'],
    platforms:['amazon','taobao','shopify','temu'],
    tips:'Outdoor: location shots, gear detail in context, weather proofing demo, weight/pack size.',
    zhTips:'户外：实景拍摄，装备细节展示，防水测试，重量/收纳尺寸。'},
  { id:'baby',en:'Baby & Maternity',zh:'母婴',icon:'Baby',cat:'official',
    kw:['baby','infant','toddler','diaper','stroller','bottle','onesie','crib','maternity','婴儿','幼儿','尿布','推车','奶瓶','连体衣','婴儿床','孕妇'],
    visual:'Soft pastel tones, natural window light, baby modeling (safety first), parent-baby interaction. Gentle, trustworthy aesthetic.',
    zhVisual:'柔和粉彩色调，自然窗光，婴儿模特（安全第一），亲子互动。温柔可信赖。',
    sp:['BPA-free','Organic cotton','Safety certified','Hypoallergenic','Pediatrician approved','Machine washable','Non-toxic'],
    zhSP:['不含BPA','有机棉','安全认证','低敏','儿科医生推荐','可机洗','无毒'],
    term:['Newborn','Breathable','Swaddle','Ergonomic','Convertible','Travel system'],
    zhTerm:['新生儿','透气','襁褓','人体工学','可转换','旅行系统'],
    comp:['Pampers','Johnson\'s','Fisher-Price','Avent','全棉时代'],
    platforms:['amazon','taobao','shopee','temu','shopify'],
    tips:'Baby: safety certifications visible, scale reference, material close-up, parent-baby use shot.',
    zhTips:'母婴：安全认证标识，尺寸参照，材质特写，亲子使用场景。'},
  { id:'toy',en:'Toys & Games',zh:'玩具',icon:'Gamepad2',cat:'official',
    kw:['toy','game','puzzle','doll','action figure','lego','board game','remote control','玩具','游戏','拼图','娃娃','手办','乐高','桌游','遥控'],
    visual:'Playful colorful setup, child interaction (with consent), unboxing-style flat lays. Bright vibrant colors, fun energy.',
    zhVisual:'趣味彩色布置，儿童互动（授权），开箱式平铺。明亮鲜艳色彩，欢乐活力。',
    sp:['STEM educational','Developmental','Non-toxic','Durable','Award-winning','Interactive','Screen-free'],
    zhSP:['STEAM教育','智力开发','无毒安全','耐玩','获奖产品','互动','无屏幕'],
    term:['Montessori','Sensory','Motor skills','Puzzle','Building blocks','Collectible','RC'],
    zhTerm:['蒙台梭利','感官','精细动作','拼图','积木','收藏','遥控'],
    comp:['LEGO','Mattel','Hasbro','Fisher-Price','万代'],
    platforms:['amazon','taobao','shopee','temu'],
    tips:'Toys: unboxing, child playing, close-up of features, size reference, age recommendation.',
    zhTips:'玩具：开箱展示，儿童玩耍，功能特写，尺寸参照，年龄建议。'},
  { id:'automotive',en:'Automotive',zh:'汽配',icon:'Car',cat:'official',
    kw:['car','auto','engine','oil','filter','brake','tire','mirror','camera dash','汽车','发动机','机油','滤芯','刹车','轮胎','后视镜','行车记录仪'],
    visual:'Clean garage/studio setting, technical detail shots, before/after installation, lifestyle: car in action. Technical yet premium.',
    zhVisual:'干净车库/影棚，技术细节特写，安装前后对比。技术感+高级感。',
    sp:['OEM quality','High performance','Durable','Easy install','Weather resistant','Noise reduction','Universal fit'],
    zhSP:['原厂品质','高性能','耐用','易安装','耐候','降噪','通用适配'],
    term:['OEM','Aftermarket','Horsepower','Torque','Lubrication','Brake pad','Suspension'],
    zhTerm:['原厂','售后件','马力','扭矩','润滑','刹车片','悬挂'],
    comp:['Bosch','Michelin','Castrol','3M','Brembo'],
    platforms:['amazon','ebay','taobao','shopee'],
    tips:'Automotive: fitment chart essential, installation video, product detail in context, certifications.',
    zhTips:'汽配：适配表必填，安装视频，产品细节，认证标识。'},
  { id:'medical',en:'Medical & Health',zh:'医疗健康',icon:'HeartPulse',cat:'official',
    kw:['medical','health','vitamin','supplement','mask','thermometer','test kit','blood pressure','医疗','健康','维生素','保健品','口罩','体温计','检测','血压'],
    visual:'Clean clinical setting, white medical background, instructional use graphics, packaging close-up. Trustworthy professional aesthetic.',
    zhVisual:'干净临床环境，白色医疗背景，使用说明图，包装特写。专业可信赖。',
    sp:['FDA approved','Clinically tested','Doctor recommended','Sterile','Latex-free','CE certified','ISO standard'],
    zhSP:['FDA认证','临床验证','医生推荐','无菌','无乳胶','CE认证','ISO标准'],
    term:['Disposable','Reusable','Single-use','Antibacterial','Probiotic','Vital signs','Diagnostic'],
    zhTerm:['一次性','可重复','单次使用','抗菌','益生菌','生命体征','诊断'],
    comp:['3M','Medtronic','Johnson & Johnson','欧姆龙','鱼跃'],
    platforms:['amazon','taobao','shopee'],
    tips:'Medical: certifications prominent, usage instructions clear, sterile packaging shown.',
    zhTips:'医疗：认证标识醒目，使用说明清晰，无菌包装展示。'},
  { id:'books',en:'Books',zh:'图书',icon:'BookOpen',cat:'community',
    kw:['book','ebook','audiobook','notebook','journal','planner','novel','textbook','书','电子书','有声书','笔记本','日记','计划本','小说','教材'],
    visual:'Creative flat-lay book photography, reading nook context, cover design close-up, spine + spread shots. Literary cozy aesthetic.',
    zhVisual:'创意平铺书摄影，阅读角落场景，封面特写，书脊+内页。文艺温馨。',
    sp:['Bestseller','Award-winning author','Premium paper','Hardcover edition','Illustrated','Signed copy','Collector edition'],
    zhSP:['畅销书','获奖作者','优质纸张','精装版','插图版','签名版','收藏版'],
    term:['Hardcover','Paperback','Audiobook','Dust jacket','Bookmark','Reading journal'],
    zhTerm:['精装','平装','有声书','书封','书签','读书笔记'],
    comp:['Penguin','HarperCollins','Amazon Publishing','中信','读客'],
    platforms:['amazon','taobao','shopify'],
    tips:'Books: cover front+back, spine, a few interior spreads, lifestyle reading shot.',
    zhTips:'图书：封面+封底+书脊，内页预览，阅读场景。'},
  { id:'digital-product',en:'Digital Product',zh:'数字产品',icon:'Monitor',cat:'community',
    kw:['software','app','template','preset','ebook','course','plugin','AI','软件','模板','预设','电子书','课程','插件'],
    visual:'Clean UI mockups on devices, dashboard screenshots, before/after workflow, animated demo GIFs. Sleek modern tech aesthetic.',
    zhVisual:'设备界面展示，后台截图，前后对比，动态Demo。科技现代感。',
    sp:['Instant download','Lifetime access','Free updates','24/7 support','Money-back','One-click','No code'],
    zhSP:['即时下载','终身访问','免费更新','全天候支持','退款保证','一键操作','零代码'],
    term:['SaaS','API','Plugin','Template','Dashboard','Automation','Integration','Cloud-based'],
    zhTerm:['SaaS','API','插件','模板','仪表盘','自动化','集成','云端'],
    comp:['Notion','Figma','Canva','Gumroad','Product Hunt'],
    platforms:['shopify','amazon','gumroad'],
    tips:'Digital: UI screenshots, feature GIFs, workflow diagrams, comparison tables.',
    zhTips:'数字产品：界面截图，功能GIF，流程图，对比表。'},
];

/* ═══════════════════════════════════════════════════════════════════
   Brands (23)
   ═══════════════════════════════════════════════════════════════════ */
const brands = [
  { id:'apple',en:'Apple',zh:'苹果风格',cat:'brand',
    desc:'Minimalist, clean, product-focused. White space, precision, understated elegance.',
    zhDesc:'极简、干净、产品为先。留白、精准、低调优雅。',
    icon:'Apple',
    palette:['#F5F5F7','#1D1D1F','#86868B','#0071E3','#FFFFFF','#000000'],
    mood:'Minimalist perfection, quiet confidence',zhMood:'极简完美，安静自信',
    lighting:'Clean studio lighting, soft shadows, high-key',zhLighting:'干净影棚光，柔影，高调',
    composition:'Centered composition, generous negative space, product isolation',zhComposition:'居中构图，大量留白，产品独立',
    kw:['minimal','clean','premium','white space','precision','sleek','elegant'],
    zhKW:['极简','干净','高级','留白','精准','流畅','优雅'],
    tone:'Confident, concise, aspirational. "Think different."',zhTone:'自信、简洁、有追求的。"不同凡想。"',
    samples:['Simplicity is the ultimate sophistication.','Designed to be unmistakably yours.'],
    zhSamples:['简约，是极致的复杂。','为独一无二的你而设计。'],
    bestFor:['electronics','watch','digital-product'] },
  { id:'nike',en:'Nike',zh:'耐克风格',cat:'brand',
    desc:'Athletic, bold, motivational. Dynamic action, high contrast, performance-driven.',
    zhDesc:'运动、大胆、激励。动态动作，高对比度，性能导向。',
    icon:'Activity',
    palette:['#111111','#FFFFFF','#FF5000','#8A8D8F','#FA5400'],
    mood:'Energetic, unstoppable, champion mindset',zhMood:'活力无限，不可阻挡，冠军心态',
    lighting:'Dramatic directional lighting, rim lights, sweat highlights',zhLighting:'戏剧方向光，轮廓光，汗水高光',
    composition:'Dynamic angles, motion blur, athlete in action',zhComposition:'动态角度，运动模糊，运动员动作中',
    kw:['athletic','bold','dynamic','performance','motivation','action','energy'],
    zhKW:['运动','大胆','动态','性能','激励','行动','能量'],
    tone:'Motivational, direct, empowering. "Just Do It."',zhTone:'激励、直接、赋能的。"只管去做。"',
    samples:['Just Do It.','There is no finish line.'],
    zhSamples:['只管去做。','没有终点线。'],
    bestFor:['sports','shoes','fashion','outdoor'] },
  { id:'adidas',en:'Adidas',zh:'阿迪达斯风格',cat:'brand',
    desc:'Street-meets-sport, urban energy, three-stripe identity. Bold graphics.',
    zhDesc:'街头遇见运动，城市能量，三道杠标识。大胆图形。',
    icon:'Move',
    palette:['#000000','#FFFFFF','#ED1C24','#2D9B41','#0066B3'],
    mood:'Urban athletic, street culture, authentic',zhMood:'城市运动，街头文化，真实',
    lighting:'Urban ambient, neon accents, gritty yet clean',zhLighting:'城市环境光，霓虹点缀，粗粝而干净',
    composition:'Street context, group energy, lifestyle over studio',zhComposition:'街头场景，群体活力，生活方式优先影棚',
    kw:['street','urban','sport','culture','bold','three stripes','authentic'],
    zhKW:['街头','城市','运动','文化','大胆','三道杠','真实'],
    tone:'Authentic, street-smart, inclusive. "Impossible is nothing."',zhTone:'真实、街头智慧、包容的。"没有不可能。"',
    samples:['Impossible is nothing.','Here to create.'],
    zhSamples:['没有不可能。','为创造而来。'],
    bestFor:['sports','shoes','fashion'] },
  { id:'muji',en:'MUJI',zh:'无印良品风格',cat:'brand',
    desc:'Japanese minimalism, no-brand quality, natural materials. Warm simplicity.',
    zhDesc:'日式极简，无品牌品质，天然材料。温暖简约。',
    icon:'Leaf',
    palette:['#F5F3F0','#8B4513','#2F4F2F','#D3D3D3','#FFFFFF','#4A3728'],
    mood:'Calm, simple, honest, natural',zhMood:'平静、简单、真诚、自然',
    lighting:'Soft diffused natural light, no harsh shadows, warm tones',zhLighting:'柔和散射自然光，无硬影，暖色调',
    composition:'Simple, uncluttered, natural materials visible',zhComposition:'简洁无杂乱，天然材料可见',
    kw:['minimal','natural','Japanese','simple','clean','warm','honest'],
    zhKW:['极简','自然','日式','简约','干净','温暖','真诚'],
    tone:'Gentle, sincere, understated. "That\'s enough."',zhTone:'温柔、真诚、克制的。"这样就好。"',
    samples:['Less is more.','Simple, functional beauty.'],
    zhSamples:['少即是多。','简约实用的美。'],
    bestFor:['home-decor','furniture','kitchen','skincare','fashion'] },
  { id:'uniqlo',en:'UNIQLO',zh:'优衣库风格',cat:'brand',
    desc:'LifeWear philosophy, functional basics, clean casual. Bright and friendly.',
    zhDesc:'服适人生哲学，功能基础款，干净休闲。明亮友好。',
    icon:'Shirt',
    palette:['#E50010','#FFFFFF','#1A1A1A','#F5F5F5','#B0B0B0'],
    mood:'Friendly, accessible, modern life essentials',zhMood:'友好、平易近人、现代生活必需品',
    lighting:'Bright even lighting, clean shadows, product flat-lay',zhLighting:'明亮均匀光照，干净阴影，平铺展示',
    composition:'Clean stacking, color grouping, lifestyle layering',zhComposition:'整齐叠放，色彩分组，层次穿搭',
    kw:['lifewear','basic','functional','clean','casual','modern','affordable'],
    zhKW:['服适人生','基础款','功能','干净','休闲','现代','实惠'],
    tone:'Warm, approachable, practical. "Made for all."',zhTone:'温暖、平易近人、实用的。"为所有人而生。"',
    samples:['LifeWear: clothing designed for a better life.','Simple made better.'],
    zhSamples:['服适人生：为美好生活而设计的服装。','简约，做得更好。'],
    bestFor:['fashion','baby','home-decor'] },
  { id:'ikea',en:'IKEA',zh:'宜家风格',cat:'brand',
    desc:'Democratic design, Scandinavian simplicity, functional warmth. Bright, approachable.',
    zhDesc:'民主设计，北欧简约，功能温暖。明亮亲和。',
    icon:'Home',
    palette:['#0058A3','#FFDB00','#FFFFFF','#333333','#F5F5F5'],
    mood:'Practical, democratic, warm Scandinavian',zhMood:'实用、民主、温暖北欧',
    lighting:'Bright room-filling light, window light, warm ambient',zhLighting:'充满房间的明亮光线，窗光，温暖环境',
    composition:'Room setting, lifestyle context, assembly-friendly flat-pack',zhComposition:'房间场景，生活背景，平板包装',
    kw:['scandinavian','democratic','practical','bright','family','affordable','clever'],
    zhKW:['北欧','民主','实用','明亮','家庭','实惠','巧妙'],
    tone:'Practical, clever, warm. "The wonderful everyday."',zhTone:'实用、巧妙、温暖的。"美好的每一天。"',
    samples:['Designed for every home.','A better everyday life.'],
    zhSamples:['为每个家而设计。','更好的日常生活。'],
    bestFor:['furniture','home-decor','kitchen','baby'] },
  { id:'dyson',en:'Dyson',zh:'戴森风格',cat:'brand',
    desc:'Engineering beauty, futuristic form, technical precision. Silver, purple, dramatic.',
    zhDesc:'工程之美，未来形态，技术精准。银色、紫色、戏剧化。',
    icon:'Wind',
    palette:['#4B4B4B','#D9D9D9','#6C3CBE','#0066CC','#FF3366'],
    mood:'Futuristic engineering, problem-solving beauty',zhMood:'未来感工程，解决问题的美',
    lighting:'Studio spotlight, product floating, sci-fi mood',zhLighting:'影棚聚光，产品悬浮，科幻氛围',
    composition:'Product hero, cutaway views showing internals, dramatic angles',zhComposition:'产品为主，剖面图展示内部，戏剧角度',
    kw:['engineering','innovation','futuristic','technology','precision','powerful','clean'],
    zhKW:['工程','创新','未来','科技','精准','强大','干净'],
    tone:'Technical, innovative, problem-solving. "There must be a better way."',zhTone:'技术、创新、解决问题的。"一定有更好的方式。"',
    samples:['Engineered for precision.','Solving problems others ignore.'],
    zhSamples:['为精准而设计。','解决被忽视的问题。'],
    bestFor:['electronics','beauty','home-decor'] },
  { id:'starbucks',en:'Starbucks',zh:'星巴克风格',cat:'brand',
    desc:'Third-place warmth, coffee craft, seasonal storytelling. Green, warm earth tones.',
    zhDesc:'第三空间温暖，咖啡手艺，季节故事。绿色、温暖大地色。',
    icon:'Coffee',
    palette:['#006241','#D4E9E2','#FFFFFF','#CBA258','#1E3932'],
    mood:'Warm, inviting, crafted, community',zhMood:'温暖、邀请、精心制作、社区',
    lighting:'Warm café lighting, golden hour, steam/mist atmosphere',zhLighting:'温暖咖啡厅灯光，黄金时刻，蒸汽氛围',
    composition:'Close-up drinks, hands holding cup, café environment',zhComposition:'饮品特写，手持杯子，咖啡厅环境',
    kw:['coffee','warm','craft','community','seasonal','comfort','ritual'],
    zhKW:['咖啡','温暖','手艺','社区','季节','舒适','仪式感'],
    tone:'Warm, personal, crafted. "The third place."',zhTone:'温暖、个人、精心制作的。"第三空间。"',
    samples:['Crafted with care.','More than just coffee.'],
    zhSamples:['用心制作。','不只是咖啡。'],
    bestFor:['food','drinks','kitchen'] },
  { id:'lego',en:'LEGO',zh:'乐高风格',cat:'brand',
    desc:'Playful creativity, brick-by-brick, colorful precision. Joy, imagination, endless possibilities.',
    zhDesc:'趣味创意，积木搭建，色彩精准。欢乐、想象、无限可能。',
    icon:'Box',
    palette:['#FF0000','#FECF00','#0051FF','#00852B','#FFFFFF'],
    mood:'Playful, creative, joyful, precise',zhMood:'趣味、创意、欢乐、精准',
    lighting:'Bright, colorful, shadow-free product lighting',zhLighting:'明亮、多彩、无影产品光',
    composition:'Clean product on white, step-by-step build, action play scene',zhComposition:'白底产品，步骤搭建，玩乐场景',
    kw:['creative','playful','colorful','build','imagination','brick','precision'],
    zhKW:['创意','趣味','多彩','搭建','想象力','积木','精准'],
    tone:'Playful, imaginative, empowering. "Rebuild the world."',zhTone:'趣味、想象力、赋能的。"重建世界。"',
    samples:['Only the best is good enough.','Play is learning.'],
    zhSamples:['只有最好的才算足够好。','玩耍就是学习。'],
    bestFor:['toy','baby'] },
  { id:'louis-vuitton',en:'Louis Vuitton',zh:'LV风格',cat:'brand',
    desc:'Travel heritage, monogram luxury, craftsmanship excellence. Rich browns, gold, timeless.',
    zhDesc:'旅行传承，字母组合奢华，工艺卓越。浓郁棕色、金色、永恒。',
    icon:'Crown',
    palette:['#8A6D3B','#4A2C2A','#D4AF37','#FFFFFF','#2C1810'],
    mood:'Heritage luxury, timeless elegance, savoir-faire',zhMood:'传承奢华，永恒优雅，精湛技艺',
    lighting:'Warm dramatic lighting, velvet backdrop, jewelry-box glow',zhLighting:'温暖戏剧光，丝绒背景，珠宝盒光芒',
    composition:'Product hero, lifestyle travel, craftsmanship detail',zhComposition:'产品为主，旅行场景，工艺细节',
    kw:['luxury','heritage','monogram','travel','craft','excellence','timeless'],
    zhKW:['奢华','传承','字母组合','旅行','工艺','卓越','永恒'],
    tone:'Sophisticated, aspirational, legacy. "The art of travel."',zhTone:'精致、有追求、传承的。"旅行的艺术。"',
    samples:['The art of travel.','Every detail matters.'],
    zhSamples:['旅行的艺术。','每个细节都很重要。'],
    bestFor:['bags','fashion','jewelry','watch'] },
  { id:'hermes',en:'Hermès',zh:'爱马仕风格',cat:'brand',
    desc:'Ultimate craftsmanship, saddle-stitch heritage, orange box luxury. Timeless artistry.',
    zhDesc:'极致工艺，马鞍缝制传承，橙色礼盒奢华。永恒艺术。',
    icon:'Award',
    palette:['#FF6A00','#4A2C2A','#EEDDCC','#FFFFFF','#8B4513'],
    mood:'Artisanal luxury, quiet wealth, artistic heritage',zhMood:'匠人奢华，低调财富，艺术传承',
    lighting:'Soft gallery lighting, warm amber, cinematic',zhLighting:'柔和画廊光，温暖琥珀色，电影感',
    composition:'Artistic product placement, craft-in-progress, detail extreme close-up',zhComposition:'艺术产品摆放，手工过程，极致细节特写',
    kw:['artisan','craft','luxury','heritage','saddle','silk','orange box'],
    zhKW:['匠人','工艺','奢华','传承','马鞍','丝绸','橙色礼盒'],
    tone:'Refined, artistic, exclusive. "Le temps devant soi."',zhTone:'精致、艺术、独享的。"时间在眼前。"',
    samples:['Craftsmanship is patience.','Nothing is by chance.'],
    zhSamples:['工艺就是耐心。','没有偶然。'],
    bestFor:['bags','fashion','jewelry','watch'] },
  { id:'chanel',en:'Chanel',zh:'香奈儿风格',cat:'brand',
    desc:'Timeless elegance, black & white, pearls, tweed. Feminine power, classic sophistication.',
    zhDesc:'永恒优雅，黑白配色，珍珠、粗花呢。女性力量，经典精致。',
    icon:'Sparkles',
    palette:['#000000','#FFFFFF','#F2E3C6','#B88A5F','#D4AF37'],
    mood:'Timeless, sophisticated, feminine strength',zhMood:'永恒、精致、女性力量',
    lighting:'Soft glamour lighting, pearl reflection, high-contrast B&W',zhLighting:'柔和魅力光，珍珠反射，高对比黑白',
    composition:'Classic symmetry, iconic elements (camellia, pearl), portrait elegance',zhComposition:'经典对称，标志元素（山茶花、珍珠），肖像优雅',
    kw:['elegance','timeless','pearls','black-white','feminine','classic','sophisticated'],
    zhKW:['优雅','永恒','珍珠','黑白','女性','经典','精致'],
    tone:'Confident, timeless, iconic. "In order to be irreplaceable..."',zhTone:'自信、永恒、标志性的。"为了无可替代..."',
    samples:['Simplicity is the keynote of all true elegance.','Fashion fades, only style remains.'],
    zhSamples:['简约是一切真正优雅的主调。','时尚易逝，风格永存。'],
    bestFor:['fashion','beauty','jewelry','skincare'] },
  { id:'dior',en:'Dior',zh:'迪奥风格',cat:'brand',
    desc:'New Look elegance, floral romance, couture dreams. Romantic luxury, star-pattern magic.',
    zhDesc:'新风貌优雅，花卉浪漫，高定梦幻。浪漫奢华，星形魔法。',
    icon:'Flower',
    palette:['#2C2C2C','#F5E6D3','#D4AF37','#C41E3A','#FFFFFF'],
    mood:'Romantic, feminine, couture dream',zhMood:'浪漫、女性、高定之梦',
    lighting:'Soft romantic lighting, candlelight glow, perfume-bottle light',zhLighting:'柔和浪漫光，烛光辉映，香水瓶光芒',
    composition:'Floral elements, architectural fashion, dreamy atmosphere',zhComposition:'花卉元素，建筑轮廓服装，梦幻氛围',
    kw:['romance','flowers','couture','luxury','feminine','dream','star'],
    zhKW:['浪漫','花卉','高定','奢华','女性','梦幻','星星'],
    tone:'Romantic, aspirational, magical. "J\'adore."',zhTone:'浪漫、有追求、魔法的。"真我。"',
    samples:['The magic of couture.','After women, flowers are the most divine creations.'],
    zhSamples:['高定的魔法。','继女人之后，花朵是最神圣的造物。'],
    bestFor:['fashion','beauty','skincare','jewelry'] },
  { id:'minimal',en:'Minimal',zh:'极简风',cat:'style',
    desc:'Pure minimalism, maximum negative space, single focal point. Less is more.',
    zhDesc:'纯粹极简，极致留白，单一焦点。少即是多。',
    icon:'Minus',
    palette:['#FAFAFA','#1A1A1A','#EBEBEB','#000000','#FFFFFF'],
    mood:'Pure, calm, essential, meditative',zhMood:'纯净、平静、本质、冥想',
    lighting:'Soft diffused, shadowless or single soft shadow',zhLighting:'柔和散射，无影或单一柔影',
    composition:'Centered, breathing room, single hero element',zhComposition:'居中，呼吸空间，单一主角',
    kw:['minimal','clean','pure','simple','essential','white space','calm'],
    zhKW:['极简','干净','纯净','简约','本质','留白','平静'],
    tone:'Quiet, essential, precise. Fewer words.',zhTone:'安静、本质、精准的。少言寡语。',
    samples:['Less, but better.','Essential only.'],
    zhSamples:['少，但是更好。','唯本质。'],
    bestFor:['electronics','home-decor','skincare','digital-product'] },
  { id:'luxury',en:'Luxury',zh:'奢华风',cat:'style',
    desc:'Opulent, gold-accented, dramatic lighting. Rich textures, aspirational lifestyle.',
    zhDesc:'华丽、金色点缀、戏剧光线。丰富纹理，向往的生活方式。',
    icon:'Gem',
    palette:['#1A1A1A','#D4AF37','#2C1810','#FFFFFF','#8A6D3B'],
    mood:'Opulent, aspirational, exclusive, grand',zhMood:'华丽、向往、专属、宏大',
    lighting:'Dramatic spotlight, jewelry-box lighting, golden hour',zhLighting:'戏剧聚光，珠宝盒光，黄金时刻',
    composition:'Dramatic angle, depth of field, product as hero',zhComposition:'戏剧角度，浅景深，产品为主',
    kw:['luxury','gold','opulent','exclusive','premium','dramatic','rich'],
    zhKW:['奢华','金色','华丽','专属','高级','戏剧','丰富'],
    tone:'Exclusive, aspirational, grand. For the discerning.',zhTone:'专属、向往、宏大的。为鉴赏者而设。',
    samples:['The pinnacle of craft.','Reserved for the few.'],
    zhSamples:['工艺的巅峰。','仅为少数人。'],
    bestFor:['jewelry','watch','bags','fashion'] },
  { id:'cyberpunk',en:'Cyberpunk',zh:'赛博朋克',cat:'style',
    desc:'Neon-lit, dystopian future, tech-noir aesthetic. Purple/cyan, rain, holograms.',
    zhDesc:'霓虹照亮，反乌托邦未来，科技黑色美学。紫/青色，雨，全息。',
    icon:'Zap',
    palette:['#0D0221','#FF00FF','#00FFFF','#FF6600','#1A1A2E'],
    mood:'Rebellious, futuristic, edgy, digital',zhMood:'反叛、未来、前卫、数字化',
    lighting:'Neon signs, rain reflections, volumetric fog, cyber lighting',zhLighting:'霓虹灯牌，雨中反射，体积雾，赛博灯光',
    composition:'Low angle, neon reflections, tech interfaces overlay',zhComposition:'低角度，霓虹反射，科技界面叠加',
    kw:['neon','dystopian','tech','digital','edgy','hologram','night'],
    zhKW:['霓虹','反乌托邦','科技','数字','前卫','全息','黑夜'],
    tone:'Rebellious, digital, underground. "Wake up, samurai."',zhTone:'反叛、数字、地下的。"醒醒，武士。"',
    samples:['The future is now.','Break the code.'],
    zhSamples:['未来已来。','打破代码。'],
    bestFor:['electronics','digital-product','fashion'] },
  { id:'modern',en:'Modern',zh:'现代风',cat:'style',
    desc:'Contemporary, architectural, clean lines. Neutral palette, geometric precision.',
    zhDesc:'当代、建筑感、干净线条。中性色调，几何精准。',
    icon:'Building',
    palette:['#FFFFFF','#2D2D2D','#E5E5E5','#B4382A','#5D737E'],
    mood:'Contemporary, sophisticated, architectural',zhMood:'当代、精致、建筑感',
    lighting:'Clean architectural lighting, natural window light',zhLighting:'干净建筑光，自然窗光',
    composition:'Geometric, structured, spatial awareness',zhComposition:'几何、结构、空间感',
    kw:['modern','clean','geometric','architectural','contemporary','structured','professional'],
    zhKW:['现代','干净','几何','建筑','当代','结构','专业'],
    tone:'Professional, contemporary, confident.',zhTone:'专业、当代、自信的。',
    samples:['Form follows function.','Timeless contemporary.'],
    zhSamples:['形式追随功能。','永恒的当代。'],
    bestFor:['furniture','home-decor','electronics','digital-product'] },
  { id:'natural',en:'Natural',zh:'自然风',cat:'style',
    desc:'Organic, earthy, botanical. Natural materials, sunlight, sustainable vibes.',
    zhDesc:'有机、大地、植物。天然材料，阳光，可持续感。',
    icon:'Leaf',
    palette:['#F0EDE5','#4A6741','#8B7355','#D4C5B2','#2D4A22'],
    mood:'Organic, calm, sustainable, earthy',zhMood:'有机、宁静、可持续、大地',
    lighting:'Golden hour sunlight, dappled shade, window light',zhLighting:'黄金时刻阳光，斑驳树影，窗光',
    composition:'Organic shapes, botanical elements, natural context',zhComposition:'有机形态，植物元素，自然场景',
    kw:['natural','organic','earthy','botanical','sustainable','calm','warm'],
    zhKW:['自然','有机','大地','植物','可持续','宁静','温暖'],
    tone:'Warm, grounded, honest. From nature.',zhTone:'温暖、扎实、真诚的。源于自然。',
    samples:['Inspired by nature.','Pure and simple.'],
    zhSamples:['源于自然的灵感。','纯粹而简单。'],
    bestFor:['skincare','food','home-decor','baby'] },
  { id:'japanese',en:'Japanese',zh:'日式风',cat:'style',
    desc:'Wabi-sabi, zen aesthetics, imperfection beauty. Muted tones, natural materials, calm.',
    zhDesc:'侘寂、禅意美学、不完美之美。柔和色调，天然材料，宁静。',
    icon:'Circle',
    palette:['#F5F0E8','#3B3B3B','#8B7D6B','#D4CFC4','#6B5B4F'],
    mood:'Zen, wabi-sabi, quiet, contemplative',zhMood:'禅、侘寂、安静、沉思',
    lighting:'Soft diffused natural light, gentle shadows, lantern glow',zhLighting:'柔和散射自然光，轻柔阴影，灯笼辉光',
    composition:'Asymmetrical balance, empty space (ma), natural texture focus',zhComposition:'不对称平衡，间（留白），天然纹理焦点',
    kw:['zen','wabi-sabi','quiet','contemplative','natural','asymmetrical','texture'],
    zhKW:['禅','侘寂','安静','沉思','自然','不对称','纹理'],
    tone:'Quiet, contemplative, poetic. Beauty in imperfection.',zhTone:'安静、沉思、诗意的。不完美之美。',
    samples:['Beauty in imperfection.','Stillness speaks.'],
    zhSamples:['不完美中的美。','静默有声。'],
    bestFor:['home-decor','skincare','kitchen','fashion'] },
  { id:'nordic',en:'Nordic',zh:'北欧风',cat:'style',
    desc:'Scandinavian hygge, cozy minimalism, light woods. Soft, bright, functional beauty.',
    zhDesc:'斯堪的纳维亚 hygge，舒适极简，浅色木材。柔和、明亮、功能之美。',
    icon:'Sun',
    palette:['#FFFFFF','#F5F0EB','#D4C8BE','#7D8B7A','#3A4D44'],
    mood:'Cozy, bright, functional, warm minimalism',zhMood:'舒适、明亮、功能、温暖极简',
    lighting:'Soft natural window light, candlelight, warm and inviting',zhLighting:'柔和自然窗光，烛光，温暖宜人',
    composition:'Layered textures, lived-in warmth, functional arrangement',zhComposition:'层次纹理，生活温暖感，功能布局',
    kw:['hygge','cozy','bright','functional','scandinavian','warm','light'],
    zhKW:['hygge','舒适','明亮','功能','斯堪的纳维亚','温暖','光线'],
    tone:'Warm, inviting, practical. Create hygge.',zhTone:'温暖、邀请、实用的。创造 hygge。',
    samples:['Light and comfort.','Simple joys.'],
    zhSamples:['光与舒适。','简单的快乐。'],
    bestFor:['furniture','home-decor','kitchen','baby'] },
  { id:'dark',en:'Dark',zh:'暗黑风',cat:'style',
    desc:'Moody, dramatic, mysterious. Deep blacks, single light source, high contrast.',
    zhDesc:'情绪化、戏剧、神秘。深黑色，单一光源，高对比。',
    icon:'Moon',
    palette:['#000000','#1A1A1A','#2C2C2C','#F5F5F5','#8A0303'],
    mood:'Mysterious, dramatic, powerful, intense',zhMood:'神秘、戏剧、力量、强烈',
    lighting:'Single dramatic light source, chiaroscuro, deep shadows',zhLighting:'单一戏剧光源，明暗对比法，深阴影',
    composition:'Dramatic negative space, light sculpting form, noir aesthetic',zhComposition:'戏剧留白，光线雕刻形态，黑色电影美学',
    kw:['dark','moody','dramatic','mysterious','noir','intense','powerful'],
    zhKW:['暗黑','情绪','戏剧','神秘','黑色电影','强烈','力量'],
    tone:'Intense, mysterious, powerful. Darkness reveals.',zhTone:'强烈、神秘、有力的。黑暗揭示。',
    samples:['Embrace the dark.','Light exists because of shadow.'],
    zhSamples:['拥抱黑暗。','光因影而存在。'],
    bestFor:['fashion','jewelry','watch','electronics'] },
  { id:'future',en:'Future',zh:'未来风',cat:'style',
    desc:'Sci-fi utopian, holographic, iridescent. Chrome, glass, floating elements.',
    zhDesc:'科幻乌托邦，全息，虹彩。铬色、玻璃、悬浮元素。',
    icon:'Globe',
    palette:['#E8E8E8','#C0C0C0','#87CEEB','#DDA0DD','#B0E0E6'],
    mood:'Utopian, innovative, boundaryless, holographic',zhMood:'乌托邦、创新、无界、全息',
    lighting:'Holographic reflections, volumetric light, iridescent glow',zhLighting:'全息反射，体积光，虹彩光芒',
    composition:'Floating elements, glass and chrome reflections, digital overlay',zhComposition:'悬浮元素，玻璃和铬反射，数字叠加',
    kw:['futuristic','holographic','iridescent','chrome','glass','utopian','digital'],
    zhKW:['未来','全息','虹彩','铬色','玻璃','乌托邦','数字'],
    tone:'Visionary, boundary-pushing, optimistic. Tomorrow, today.',zhTone:'远见、突破边界、乐观的。明天即今天。',
    samples:['The future is beautiful.','Beyond imagination.'],
    zhSamples:['未来是美丽的。','超越想象。'],
    bestFor:['electronics','digital-product','beauty'] },
  { id:'generic',en:'Generic',zh:'通用',cat:'style',
    desc:'Adaptable, neutral, professional. Works across categories without strong stylistic identity.',
    zhDesc:'灵活、中性、专业。跨品类适用，无明显风格特征。',
    icon:'Palette',
    palette:['#FFFFFF','#333333','#F5F5F5','#666666','#CCCCCC'],
    mood:'Professional, neutral, adaptable',zhMood:'专业、中性、灵活',
    lighting:'Clean professional studio lighting',zhLighting:'干净专业影棚光',
    composition:'Standard e-commerce product composition',zhComposition:'标准电商产品构图',
    kw:['professional','neutral','clean','adaptable','standard','universal','generic'],
    zhKW:['专业','中性','干净','灵活','标准','通用'],
    tone:'Professional, helpful, straightforward.',zhTone:'专业、有用、直接的。',
    samples:['Made for you.','Quality you can trust.'],
    zhSamples:['为你而作。','值得信赖的品质。'],
    bestFor:['fashion','electronics','home-decor','kitchen','books'] },
];

/* ═══════════════════════════════════════════════════════════════════
   Write files
   ═══════════════════════════════════════════════════════════════════ */

const industryBarrel = [];

for (const ind of industries) {
  const file = `import { IndustrySkill } from '../types';

export const ${ind.id}Industry: IndustrySkill = {
  type: 'industry',
  id: '${ind.id}',
  name: '${ind.en}',
  zhName: '${ind.zh}',
  category: '${ind.cat}',
  icon: '${ind.icon}',
  description: '${ind.desc || `AI-optimized ${ind.en} product photography, copywriting, and marketing content generation.`}',
  zhDescription: '${ind.zhDesc || `AI 优化的${ind.zh}产品摄影、文案和营销内容生成。`}',
  keywords: ${JSON.stringify(ind.kw)},
  typicalSpecs: {
${ind.id === 'digital-product' ? '    tips: "UI screenshots, feature GIFs, workflow diagrams, comparison tables.",\n    zhTips: "界面截图，功能GIF，流程图，对比表。",' : `    imageSize: { width: 800, height: 800 },
    videoFormat: '${ind.id === 'fashion' || ind.id === 'beauty' || ind.id === 'skincare' || ind.id === 'sports' || ind.id === 'jewelry' || ind.id === 'watch' ? 'vertical' : 'square'}' as const,
    commonRatios: ${JSON.stringify(ind.id === 'fashion' ? ['9:16', '4:5', '1:1'] : ind.id === 'electronics' ? ['1:1', '4:3', '16:9'] : ['1:1', '4:5', '3:4'])},
    tips: ${JSON.stringify(ind.tips)},
    zhTips: ${JSON.stringify(ind.zhTips)},`}
  },
  promptEnhancement: {
    visual: ${JSON.stringify(ind.visual)},
    zhVisual: ${JSON.stringify(ind.zhVisual)},
    sellingPoints: ${JSON.stringify(ind.sp)},
    zhSellingPoints: ${JSON.stringify(ind.zhSP)},
    terminology: ${JSON.stringify(ind.term)},
    zhTerminology: ${JSON.stringify(ind.zhTerm)},
    competitors: ${JSON.stringify(ind.comp)},
  },
  bestPlatforms: ${JSON.stringify(ind.platforms || ['taobao','amazon','shopee','shopify','tiktok'])},
};
`;
  const filePath = path.join(BASE, 'industries', `${ind.id}.ts`);
  fs.writeFileSync(filePath, file);
  industryBarrel.push(`export { ${ind.id}Industry } from './${ind.id}';`);
}

// Industry barrel
fs.writeFileSync(
  path.join(BASE, 'industries', 'index.ts'),
  industryBarrel.join('\n') + '\n'
);

// Industry registry helper
const registryCode = `import { IndustrySkillRegistry, IndustrySkillId } from '../types';
${industryBarrel.map(l => l.replace('export ', 'import ')).join('\n')}

export const industryRegistry: IndustrySkillRegistry = {
${industries.map(i => `  '${i.id}': ${i.id}Industry,`).join('\n')}
};

export function getIndustry(id: IndustrySkillId) { return industryRegistry[id]; }
export function getAllIndustries() { return Object.values(industryRegistry); }
export function getIndustriesByCategory(cat: string) { return Object.values(industryRegistry).filter(s => s.category === cat); }
export const INDUSTRIES_COUNT = Object.keys(industryRegistry).length;
`;
fs.writeFileSync(path.join(BASE, 'industries', 'registry.ts'), registryCode);

// Brands
const brandBarrel = [];
for (const b of brands) {
  const file = `import { BrandSkill } from '../types';

export const ${b.id}Brand: BrandSkill = {
  type: 'brand',
  id: '${b.id}',
  name: '${b.en}',
  zhName: '${b.zh}',
  category: '${b.cat}',
  icon: '${b.icon}',
  description: '${b.desc}',
  zhDescription: '${b.zhDesc}',
  visualStyle: {
    palette: ${JSON.stringify(b.palette)},
    mood: ${JSON.stringify(b.mood)},
    zhMood: ${JSON.stringify(b.zhMood)},
    lighting: ${JSON.stringify(b.lighting)},
    zhLighting: ${JSON.stringify(b.zhLighting)},
    composition: ${JSON.stringify(b.composition)},
    zhComposition: ${JSON.stringify(b.zhComposition)},
    keywords: ${JSON.stringify(b.kw)},
    zhKeywords: ${JSON.stringify(b.zhKW)},
  },
  toneOfVoice: {
    style: ${JSON.stringify(b.tone)},
    zhStyle: ${JSON.stringify(b.zhTone)},
    samplePhrases: ${JSON.stringify(b.samples)},
    zhSamplePhrases: ${JSON.stringify(b.zhSamples)},
  },
  bestFor: ${JSON.stringify(b.bestFor)},
};
`;
  const filePath = path.join(BASE, 'brands', `${b.id}.ts`);
  fs.writeFileSync(filePath, file);
  brandBarrel.push(`export { ${b.id}Brand } from './${b.id}';`);
}

// Brand barrel
fs.writeFileSync(
  path.join(BASE, 'brands', 'index.ts'),
  brandBarrel.join('\n') + '\n'
);

// Brand registry
const brandRegCode = `import { BrandSkillRegistry, BrandSkillId } from '../types';
${brandBarrel.map(l => l.replace('export ', 'import ')).join('\n')}

export const brandRegistry: BrandSkillRegistry = {
${brands.map(b => `  '${b.id}': ${b.id}Brand,`).join('\n')}
};

export function getBrand(id: BrandSkillId) { return brandRegistry[id]; }
export function getAllBrands() { return Object.values(brandRegistry); }
export function getBrandsByCategory(cat: string) { return Object.values(brandRegistry).filter(s => s.category === cat); }
export function getBrandsForIndustry(industryId: string) { return Object.values(brandRegistry).filter(b => b.bestFor.includes(industryId as any)); }
export const BRANDS_COUNT = Object.keys(brandRegistry).length;
`;
fs.writeFileSync(path.join(BASE, 'brands', 'registry.ts'), brandRegCode);

console.log(`✅ Generated ${industries.length} industries + ${brands.length} brands`);
